---
params:
  reads_dir: "~/reads/"
  output: "~/pipeline_output/"
  min_MAG_bp_size: "500"

bin:
  clustalone: /sysapps/cluster/software/Anaconda3/2022.05/envs/vContact2-0.11.3/bin
  fmap: ~/db/FMAP
  krakentools: ~/packages/KrakenTools_v1.2
  scripts: ~/pipelines/SGSlab_metagenomics/scripts
ref:
  host_ref: ~/reference_files/mouse/GCF_000001635.27_GRCm39_genomic.fna
  card_db: ~/databases/SGSlab_metagenomics/references/card/nucleotide_fasta_protein_variant_model.fasta
  humann_db: ~/databases/SGSlab_metagenomics/references/humann
  kraken2_db: ~/databases/kraken2/20220616_hbvae
  iphop_db: ~/databases/iphop/Sept_2021_pub_rw
  megares_db: ~/databases/megares_full_database_v2.00.fasta
  metaphlan_db: ~/databases/SGSlab_metagenomics/references/metaphlan/mpa_vOct22_CHOCOPhlAnSGB_202212
  viral_nt_db: ~/databases/blast_db/viral.1.1.genomic.fna
